my:
  message : hi kimi henry dev
  context : resorse
  learn : Spring boot
server:
  port : 1101

map:
  properties: "{Name:'Henry',Age:26,Nationaity:'Indian'}"

spring.cloud.config.uri: http://localhost:9999
